### PR TITLE
python 3 migration

### PR DESCRIPTION
**Pull request by jchiang87**

### CODE REVIEW

**Comment by jchiang87** [comment]
@JoanneBogart Could you look at this one too please?  and if you could merge and tag this and `lcatr-harness` I'd appreciate it.  I'd like to get these into eT dev at IR2 very soon so that we can run early next week.

**Review by JoanneBogart — COMMENTED** [review]
The only thing I'm wondering about is the definition of is_string in __init__.py
In my local version (which I forgot to push) I had

try:
    return isinstance(o, basestring)
except NameError:
    return isinstance(o, str)

which I don't much like since it looks to satisfy 2.7 first.   But is there a problem calling your version from 2.7 if the string is in fact unicode?

**Comment by jchiang87** [comment]
I tried my version in the INT-SR-EOT-01 traveler using python 2.7 and python 3.6 and it worked in both cases, but if you want to use the `basestring` try/except tests, that's ok with me.

**Comment by JoanneBogart** [comment]
No, if yours works for both versions, might as well leave it.  I'll go ahead and merge as is.

**Pull request merged**
